export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const LAY_DANH_MUC_KHOA_HOC = "LAY_DANH_MUC_KHOA_HOC";
export const LAY_KHOA_HOC_THEO_DANH_MUC = "LAY_KHOA_HOC_THEO_DANH_MUC";
export const LAY_KHOA_HOC_THEO_TIM_KIEM = "LAY_KHOA_HOC_THEO_TIM_KIEM";
export const LAY_CHI_TIET_KHOA_HOC = "LAY_CHI_TIET_KHOA_HOC";
export const XU_LY_DANG_NHAP_THANH_CONG = "XU_LY_DANG_NHAP_THANH_CONG";
export const DANG_XUAT_TAI_KHOAN = "DANG_XUAT_TAI_KHOAN";
export const DANG_KY_KHOA_HOC = "DANG_KY_KHOA_HOC";
export const LAY_THONG_TIN_TAI_KHOAN = "LAY_THONG_TIN_TAI_KHOAN";
export const CAP_NHAT_THONG_TIN_NGUOI_DUNG = "CAP_NHAT_THONG_TIN_NGUOI_DUNG";
export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG";
export const LAY_DANH_SACH_KHOA_HOC_CHO_XAC_THUC =
  "LAY_DANH_SACH_KHOA_HOC_CHO_XAC_THUC";
export const LAY_DANH_SACH_KHOA_HOC_DA_XAC_THUC =
  "LAY_DANH_SACH_KHOA_HOC_DA_XAC_THUC";
export const LAY_DANH_SACH_KHOA_HOC_CHUA_GHI_DANH =
  "LAY_DANH_SACH_KHOA_HOC_CHUA_GHI_DANH";
export const LAY_DANH_SACH_NGUOI_DUNG_CHUA_GHI_DANH =
  "LAY_DANH_SACH_NGUOI_DUNG_CHUA_GHI_DANH";
  export const LAY_DANH_SACH_NGUOI_DUNG_CHO_XAC_THUC =
    "LAY_DANH_SACH_NGUOI_DUNG_CHO_XAC_THUC";
  export const LAY_DANH_SACH_NGUOI_DUNG_DA_XAC_THUC =
    "LAY_DANH_SACH_NGUOI_DUNG_DA_XAC_THUC";