export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const LAY_DANH_MUC_KHOA_HOC = "LAY_DANH_MUC_KHOA_HOC";
export const LAY_KHOA_HOC_THEO_DANH_MUC = "LAY_KHOA_HOC_THEO_DANH_MUC";
export const LAY_KHOA_HOC_THEO_TIM_KIEM = "LAY_KHOA_HOC_THEO_TIM_KIEM";
export const LAY_CHI_TIET_KHOA_HOC = "LAY_CHI_TIET_KHOA_HOC";
export const XU_LY_DANG_NHAP_THANH_CONG = "XU_LY_DANG_NHAP_THANH_CONG";
